---
title: "Toronto Homicides and Shootings (To be Changed)"
subtitle: "An analysis of police presence across Toronto neighbourhoods in relation to homicide and shooting cases (2018-2023)"
author: Emily Su
thanks: "Code and data are available at: https://github.com/moonsdust/toronto-homicides-shootings."
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format:
  pdf:
    toc: true
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```


# Introduction

You can and should cross-reference sections and sub-sections. We use @citeR and @rohan.

The remainder of this paper is structured as follows. @sec-data....



# Data {#sec-data}
## Methodology

## Data Source and Measurements

## Variables of Interest


# Results {#sec-results}
This is the results section

# Discussion {#sec-discussion}

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Areas of improvement

Weaknesses and next steps should also be included.

## Next steps

\newpage

\appendix

# Appendix {-}


## Acknowledgments 
We would like the acknowledge @citetellingstorieswithdata for some R code that 
was used to produce the tables and graphs.

## Note on Reproducing 
To reproduce the results in the paper, first run the scripts found in the scripts folder of the GitHub repository corresponding to the paper starting with the script, 00-install_packages.R to install the necessary packages. 

## Code styling 
Code written in the scripts was checked and styled with lintr [@citelintr] and styler [@citestyler]. 

## Additional Figures 

## Additional Tables 

\newpage


# References


